import { useEffect, useState } from "react";
import { Download, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { MarshalPerson, MarshalTrainingParticipant, MarshalWorkspace } from "@/types/admin-marshals";

type Attendance = MarshalTrainingParticipant["attendanceStatus"];
type AttendanceFilter = Attendance | "all" | "unregistered";
type Props = {
  workspace: MarshalWorkspace;
  canWrite: boolean;
  canExport: boolean;
  busy: boolean;
  onCreate: (draft: { sessionType: "training" | "briefing"; title: string; sessionDate: string; location: string | null }) => Promise<boolean>;
  onAttendance: (trainingId: string, person: MarshalPerson, status: Attendance) => Promise<boolean>;
  onRegisterAccepted: (trainingId: string, people: MarshalPerson[]) => Promise<boolean>;
  onPrint: (trainingId: string) => Promise<void>;
  onPersonOpen: (person: MarshalPerson) => void;
};

export function MarshalSchulungView({ workspace, canWrite, canExport, busy, onCreate, onAttendance, onRegisterAccepted, onPrint, onPersonOpen }: Props) {
  const [selectedId, setSelectedId] = useState("");
  const [search, setSearch] = useState("");
  const [attendance, setAttendance] = useState<AttendanceFilter>("all");
  const [draft, setDraft] = useState({ sessionType: "training" as "training" | "briefing", title: "", sessionDate: "", location: "" });
  useEffect(() => { if (!workspace.trainings.some((item) => item.id === selectedId)) setSelectedId(workspace.trainings[0]?.id ?? ""); }, [selectedId, workspace.trainings]);
  const term = search.trim().toLocaleLowerCase("de");
  const people = workspace.people.filter((person) => { const participant = workspace.trainingParticipants.find((item) => item.sessionId === selectedId && item.personId === person.id); return (!term || `${person.helperNumber} ${person.firstName} ${person.lastName} ${person.licenseNumber ?? ""}`.toLocaleLowerCase("de").includes(term)) && (attendance === "all" || (participant?.attendanceStatus ?? "unregistered") === attendance); });
  const acceptedPeopleToRegister = workspace.people.filter((person) => !person.noDeployment && person.assignments.some((assignment) => assignment.commitmentStatus === "accepted") && !workspace.trainingParticipants.some((participant) => participant.sessionId === selectedId && participant.personId === person.id));
  async function create() { const saved = await onCreate({ ...draft, location: draft.location || null }); if (saved) setDraft({ sessionType: "training", title: "", sessionDate: "", location: "" }); }

  return <div className="grid gap-4 xl:grid-cols-[340px_minmax(0,1fr)]"><Card><CardHeader className="p-4 sm:p-6"><CardTitle>Schulungen und Einweisungen</CardTitle></CardHeader><CardContent className="space-y-3 p-4 pt-0 sm:p-6 sm:pt-0"><label className="grid gap-1 text-xs font-medium text-slate-600">Termin<select className="h-10 rounded-md border bg-white px-3 text-sm font-normal" value={selectedId} onChange={(event) => setSelectedId(event.target.value)}><option value="">Kein Termin</option>{workspace.trainings.map((item) => <option key={item.id} value={item.id}>{formatDate(item.sessionDate)} · {item.title}</option>)}</select></label>{canWrite && selectedId && <Button type="button" variant="outline" className="w-full" disabled={busy || acceptedPeopleToRegister.length === 0} onClick={() => void onRegisterAccepted(selectedId, acceptedPeopleToRegister)}>Zugesagte Streckenposten anmelden ({acceptedPeopleToRegister.length})</Button>}{canExport && selectedId && <Button type="button" variant="outline" className="w-full" onClick={() => void onPrint(selectedId)}><Download className="mr-2 h-4 w-4" />Teilnehmerliste als PDF</Button>}{canWrite && <div className="space-y-2 border-t pt-4"><h3 className="font-medium">Neuer Termin</h3><label className="grid gap-1 text-xs font-medium text-slate-600">Art<select className="h-10 rounded-md border bg-white px-3 text-sm font-normal" value={draft.sessionType} onChange={(event) => setDraft({ ...draft, sessionType: event.target.value as "training" | "briefing" })}><option value="training">Lizenzschulung</option><option value="briefing">Einweisung</option></select></label><label className="grid gap-1 text-xs font-medium text-slate-600">Titel<Input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label><label className="grid gap-1 text-xs font-medium text-slate-600">Datum<Input type="date" value={draft.sessionDate} onChange={(event) => setDraft({ ...draft, sessionDate: event.target.value })} /></label><label className="grid gap-1 text-xs font-medium text-slate-600">Ort<Input value={draft.location} onChange={(event) => setDraft({ ...draft, location: event.target.value })} /></label><Button type="button" className="w-full" disabled={busy || !draft.title || !draft.sessionDate} onClick={() => void create()}><Plus className="mr-2 h-4 w-4" />Termin anlegen</Button></div>}</CardContent></Card>
    <Card><CardHeader className="p-4 sm:p-6"><CardTitle>Teilnehmer und Schulungsstatus</CardTitle></CardHeader><CardContent className="space-y-4 p-4 pt-0 sm:p-6 sm:pt-0"><div className="grid gap-2 rounded-xl border bg-slate-50 p-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-medium text-slate-600">Suche<Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Name, Nummer oder Lizenz" /></label><label className="grid gap-1 text-xs font-medium text-slate-600">Teilnahmestatus<select className="h-10 rounded-md border bg-white px-3 text-sm font-normal" value={attendance} onChange={(event) => setAttendance(event.target.value as AttendanceFilter)}><option value="all">Alle Status</option><option value="unregistered">Nicht angemeldet</option><option value="registered">Angemeldet</option><option value="attended">Anwesend</option><option value="absent">Nicht anwesend</option><option value="excused">Entschuldigt</option></select></label></div><div className="overflow-x-auto"><table className="min-w-[600px] w-full text-sm"><thead><tr className="border-b bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><th className="p-3">Name</th><th className="p-3">DMSB-Lizenz</th><th className="p-3">Teilnahmestatus</th></tr></thead><tbody>{people.map((person) => { const participant = workspace.trainingParticipants.find((item) => item.sessionId === selectedId && item.personId === person.id); return <tr key={person.id} className="border-b"><td className="p-3"><button type="button" className="font-medium text-blue-700 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" onClick={() => onPersonOpen(person)}>{person.lastName}, {person.firstName}</button>{!person.isActive && <span className="ml-2 text-xs text-slate-500">Inaktiver Stammdatensatz</span>}</td><td className="p-3">{person.licenseNumber ?? workspace.qualifications.find((item) => item.personId === person.id)?.number ?? "—"}</td><td className="p-3"><select aria-label={`Teilnahmestatus für ${person.firstName} ${person.lastName}`} className="h-10 rounded-md border bg-white px-3" value={participant?.attendanceStatus ?? ""} disabled={!canWrite || !selectedId || busy} onChange={(event) => { if (event.target.value) void onAttendance(selectedId, person, event.target.value as Attendance); }}><option value="" disabled>Nicht angemeldet</option><option value="registered">Angemeldet</option><option value="attended">Anwesend</option><option value="absent">Nicht anwesend</option><option value="excused">Entschuldigt</option></select></td></tr>; })}</tbody></table>{people.length === 0 && <p className="p-6 text-center text-sm text-slate-500">Keine Teilnehmer entsprechen den Filtern.</p>}</div></CardContent></Card></div>;
}

function formatDate(value: string) {
  return new Intl.DateTimeFormat("de-DE", { day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(`${value}T00:00:00`));
}
