export const VEHICLE_IMAGE_MAX_FILE_SIZE_BYTES = 15 * 1024 * 1024;
export const VEHICLE_IMAGE_MAX_FILE_SIZE_MB = Math.round(VEHICLE_IMAGE_MAX_FILE_SIZE_BYTES / (1024 * 1024));
export const VEHICLE_IMAGE_MAX_DIMENSION_PIXELS = 6000;
